---
- name: reload systemd
  sudo: yes
  command: systemctl --system daemon-reload

- name: restart kubelet
  sudo: yes
  service:
    name: kubelet
    state: restarted

- name: reload consul
  sudo: yes
  command: systemctl reload consul
