---
- name: write skydns pod file
  sudo: yes
  template:
    src: skydns-rc.yaml.j2
    dest: "{{ kube_manifest_dir }}/skydns-rc.yaml"
  register: dns_rc_def
  when: dns_setup
  tags:
    - addons
    - skydns
    - kubernetes

- name: create/update skydns replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: kube-dns-v8
    filename: "{{ kube_manifest_dir }}/skydns-rc.yaml"
    state: "{{ dns_rc_def.changed | ternary('latest','present') }}"
    server: "http://localhost:8085/"
  when: dns_setup
  tags:
    - addons
    - skydns
    - kubernetes
